### ISSUE TITLE
More manageable job management

### ISSUE THREAD

**Issue by electrical** [elastic/ci#12]
The openstack guys have created a project that allows us to create yaml files to create and modify jenkins jobs.
This should make it much easier to create uniform jobs and make changes to multiple jobs in a very easy way.
There are some missing parts that i'm trying to build so it could be used for it.

https://github.com/openstack-infra/jenkins-job-builder

**Comment by purbon** [comment]
+1 on that, they also have a nice view on different jobs status and how they progress.

**Comment by drewr** [comment]
Could you please create this in the infra repo so we can discuss? Thanks!

**Comment by electrical** [comment]
Moved to https://github.com/elastic/infra/issues/198
