### ISSUE TITLE
Docker reaper script interfering with normal management

### ISSUE THREAD

**Issue by mrsolo** [elastic/ci#5]
Docker cleanup script http://build-eu-00.elastic.co/view/Jenkins/job/Docker%20Cleanup/
currently will remove any node that is offline.

That needs to be restricted to docker type only

**Comment by mrsolo** [comment]
Current script

import jenkins.model.Jenkins
println "Cleaning up offline slaves..."
Jenkins.instance.slaves.each {
  if(it.getComputer().isOffline()) {
    println "Deleting ${it.name}"
    it.getComputer().doDoDelete()
  }
}
println "Done."

**Comment by mrsolo** [comment]
it.name needs to check for /.*?@docker-test

**Comment by pickypg** [comment]
You can [use the `==~` Match operator](http://docs.groovy-lang.org/latest/html/documentation/index.html#_match_operator).

```groovy
if (it.name ==~ /.*?@docker-test/) {
  // ... the name matches
}
```

**Comment by pickypg** [comment]
Incase you needed the full script (granted it's untested):

```groovy
import jenkins.model.Jenkins

println "Cleaning up offline slaves..."

Jenkins.instance.slaves.each {
  if (it.getComputer().isOffline() && it.name ==~ /.*?@docker-test/) {
    println "Deleting ${it.name}"

    it.getComputer().doDoDelete()

    println "Deleted ${it.name}"
  }
}

println "Done."
```

**Comment by mrsolo** [comment]
Started by timer
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/workspace/Docker Cleanup
Cleaning up offline slaves...
Deleting bf14a8e53784@docker-test
Done.
[Docker Cleanup] $ /bin/bash /tmp/hudson167084793871329656.sh
Finished: SUCCESS

Job modified
