### ISSUE TITLE
Upload Kibana artifacts to S3 for download

### ISSUE THREAD

**Issue by spalger** [elastic/ci#9]
We would like to offer users an option to download the latest build of Kibana, and would like to publish this build from the Jenkins job that runs on each commit.

When the tests pass, Jenkins would need to upload the contents of the `/target` directory within the Kibana project to the `download.elasticsearch.org/kibana/kibana/` bucket on s3.

If the files fail to upload, the Jenkins job should be considered "errored" but not "failed" if possible.

**Comment by mrsolo** [comment]
Do not want to give jenkins root aws credential, therefore upload/delete permission added for authenticated user to s3 bucket  download.elasticsearch.org

**Comment by spalger** [comment]
:heartbeat: :heartbeat:  https://github.com/elastic/kibana#snapshot-builds :heartbeat: :heartbeat:
